CREATE SMALLFILE TABLESPACE ISG_TABLESPACE
    DATAFILE
        'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\isg_datafile.dbf' SIZE 98304 K REUSE AUTOEXTEND ON NEXT 32768 K MAXSIZE UNLIMITED
    LOGGING
    ONLINE
    PERMANENT
    DEFAULT NOCOMPRESS
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    FLASHBACK ON
;

CREATE USER ISG
    IDENTIFIED BY ISG
    DEFAULT TABLESPACE ISG_TABLESPACE
    PROFILE DEFAULT
    ACCOUNT UNLOCK
;

GRANT EXECUTE ANY PROGRAM, CREATE ANY JOB, SELECT ANY DICTIONARY, DROP USER, ALTER USER, ALTER SYSTEM, CREATE SESSION, CREATE PUBLIC SYNONYM, DEBUG CONNECT SESSION, ALTER SESSION, CREATE ANY PROCEDURE, DROP PUBLIC SYNONYM, EXECUTE ANY PROCEDURE, CREATE TABLESPACE, DEBUG ANY PROCEDURE, ALTER DATABASE, CREATE ROLE, CREATE USER, DROP TABLESPACE TO ISG
;

GRANT CREATE ANY CONTEXT, CREATE TYPE, CREATE TRIGGER, CREATE VIEW, CREATE TABLE, CREATE JOB, CREATE CLUSTER, CREATE DIMENSION, CREATE INDEXTYPE, CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE SYNONYM, UNLIMITED TABLESPACE, CREATE OPERATOR TO ISG  WITH ADMIN OPTION
;


GRANT CREATE ANY TRIGGER TO ISG
;

GRANT DBA TO ISG
;

GRANT EXECUTE ON SYS.UTL_HTTP TO ISG
;

GRANT CREATE ANY SEQUENCE to DEV
;
