REM INSERTING into APP_SETTING
SET DEFINE OFF;
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (1,'online-url','http://80.55.103.89:8080/apex/f?p=mob',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (2,'xmpp-ip','80.55.103.89',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (3,'xmpp-port','5222',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (4,'network-high-speed','WIFI',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (5,'fullscreen','0',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (6,'autostart','1',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (7,'ws-url','http://80.55.103.89:8080/apex/wms/mobws/',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
Insert into APP_SETTING (ID,NAME,VALUE,USER_LOGIN,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (8,'work-online','0',null,1,'IOU',to_date('2013-04-22','YYYY-MM-DD'),null,null);
