REM INSERTING into APP_SOURCE
SET DEFINE OFF;
Insert into APP_SOURCE (ID,NAME,CONTENT_TYPE,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (1,'about.html','text/html',1,'IOU',to_date('2013-04-16','YYYY-MM-DD'),null,null);
Insert into APP_SOURCE (ID,NAME,CONTENT_TYPE,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (2,'jquery.min.js','application/javascript',1,'IOU',to_date('2013-04-16','YYYY-MM-DD'),null,null);
Insert into APP_SOURCE (ID,NAME,CONTENT_TYPE,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (3,'jquery.mobile.min.js','application/javascript',1,'IOU',to_date('2013-04-16','YYYY-MM-DD'),null,null);
Insert into APP_SOURCE (ID,NAME,CONTENT_TYPE,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (4,'jquery.mobile.min.css','text/css',1,'IOU',to_date('2013-04-16','YYYY-MM-DD'),null,null);
Insert into APP_SOURCE (ID,NAME,CONTENT_TYPE,VERSION,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (5,'cloud.png','image/jpeg',1,'IOU',to_date('2013-04-16','YYYY-MM-DD'),null,null);
