REM INSERTING into CUSTOMER
SET DEFINE OFF;
Insert into CUSTOMER (ID,TITLE,FIRST_NAME,LAST_NAME,COMPANY_NAME,NIP,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (3,'Mr','Andrzej','Raczkowski','SVIETE','9131448208','ADMIN',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into CUSTOMER (ID,TITLE,FIRST_NAME,LAST_NAME,COMPANY_NAME,NIP,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (22,'Pan','Sebastian','Grzyœ','SPENSA','9131234567','SK',to_date('13-JUN-13','DD-MON-RR'),null,null);
Insert into CUSTOMER (ID,TITLE,FIRST_NAME,LAST_NAME,COMPANY_NAME,NIP,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (21,'Pan','Bartosz','Bart','IBM','913-111-10-10','KURIER',to_date('13-JUN-13','DD-MON-RR'),null,null);
