REM INSERTING into CUSTOMER_ADDRESS
SET DEFINE OFF;
Insert into CUSTOMER_ADDRESS (ID,ADDRESS_ID,CUSTOMER_ID,MAIN,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (4,1,3,'Y','ADMIN',to_date('10-JUN-13','DD-MON-RR'),'ADMIN',to_date('10-JUN-13','DD-MON-RR'));
Insert into CUSTOMER_ADDRESS (ID,ADDRESS_ID,CUSTOMER_ID,MAIN,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (5,1,3,'N','ADMIN',to_date('10-JUN-13','DD-MON-RR'),'ADMIN',to_date('10-JUN-13','DD-MON-RR'));
Insert into CUSTOMER_ADDRESS (ID,ADDRESS_ID,CUSTOMER_ID,MAIN,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (21,21,21,'Y','KURIER',to_date('13-JUN-13','DD-MON-RR'),null,null);
Insert into CUSTOMER_ADDRESS (ID,ADDRESS_ID,CUSTOMER_ID,MAIN,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (22,22,22,'Y','SK',to_date('13-JUN-13','DD-MON-RR'),null,null);
