REM INSERTING into MESSAGE_TEMPLATE
SET DEFINE OFF;
Insert into MESSAGE_TEMPLATE (ID,MESSAGE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE,NOTIFICATION_CHANNEL_ID) values (1,'Kurier infrormuje, ze bedzie za 15 minut','ADMIN',to_date('10-JUN-13','DD-MON-RR'),null,null,null);
Insert into MESSAGE_TEMPLATE (ID,MESSAGE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE,NOTIFICATION_CHANNEL_ID) values (22,'By³em nie zasta³em','SK',to_date('13-JUN-13','DD-MON-RR'),null,null,null);
Insert into MESSAGE_TEMPLATE (ID,MESSAGE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE,NOTIFICATION_CHANNEL_ID) values (21,'Przynios³em przesy³kê, ale nikogo nie zasta³em w domu. Ponowne dorêczenie jutro.','SK',to_date('13-JUN-13','DD-MON-RR'),null,null,null);
