REM INSERTING into PAYMENT_TYPE
SET DEFINE OFF;
Insert into PAYMENT_TYPE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (1,'G','Gotowka','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into PAYMENT_TYPE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (2,'K','Z dolu','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into PAYMENT_TYPE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (3,'X','Zaliczkowa','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into PAYMENT_TYPE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (4,'Q','Z gory','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
