REM INSERTING into SERVICE
SET DEFINE OFF;
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (1,'B','Doreczenie w sobote','Y','K00',to_date('10-JUN-13','DD-MON-RR'),'CUR',to_date('19-DEC-12','DD-MON-RR'));
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (2,'C','Ostroznie','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (3,'D','Potwierdzenie dorêczenia albo zwrotu ','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (4,'E','Doreczenie we wskazanym dniu','Y','K00',to_date('10-JUN-13','DD-MON-RR'),'M',to_date('12-DEC-12','DD-MON-RR'));
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (5,'F','Dorêczenie do (godz) ','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (6,'G','Dorêczenie 20:00-7:00','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (7,'M','Ponadgabaryt','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (8,'P','Pobranie','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (9,'R','Dokumenty zwrotne ','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into SERVICE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (10,'Z','Dorêczenie do r¹k w³asnych','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
