REM INSERTING into TASK_STATUS
SET DEFINE OFF;
Insert into TASK_STATUS (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (6,'ANU','Anulowany','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
Insert into TASK_STATUS (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (1,'NOW','Nowy','Y','ADMIN',to_date('07-JUN-13','DD-MON-RR'),null,null);
Insert into TASK_STATUS (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (2,'ZAK','Wykonany','Y','ADMIN',to_date('07-JUN-13','DD-MON-RR'),null,null);
