REM INSERTING into TASK_TYPE
SET DEFINE OFF;
Insert into TASK_TYPE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (3,'ODB','Odebranie','Y','K00',to_date('10-JUN-13','DD-MON-RR'),'M',to_date('12-DEC-12','DD-MON-RR'));
Insert into TASK_TYPE (ID,CODE,NAME,ACTIVE,CREATION_USER,CREATION_DATE,MODIFICATION_USER,MODIFICATION_DATE) values (4,'DOS','Dostarczenie','Y','K00',to_date('10-JUN-13','DD-MON-RR'),null,null);
